In [ ]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy', #loss = mse 를 해서 구할수도 있다.
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

<module 'tensorflow.keras.datasets.mnist' from '/usr/local/lib/python3.7/dist-packages/tensorflow/keras/datasets/mnist/__init__.py'>
Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2993 - accuracy: 0.9126
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1479 - accuracy: 0.9559
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1101 - accuracy: 0.9660
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0891 - accuracy: 0.9720
Epoch 5/5
313/313 [==============================] - 0s 1ms/step - loss: 0.0702 - accuracy: 0.9773


[0.07020068913698196, 0.9772999882698059]

In [ ]:
theta_0 = 0.123
theta_1 = 1.324
x = 0.455
y_label = 15
yhat = theta_0 + (theta_1 * x)
print("y_label: {}".format(y_label))
print("yhat: {}".format(yhat))
# 값을 갱신 해야 한다.  -> 학습이라고 한다.

y_label: 15
yhat: 0.7254200000000001


MSE = 평균 제곱 오차 
현재 신경망이 얼만만큼 차이가 나는지 정량적 수치를 나타내기 위해 

In [ ]:
#문제 Mse 를 구현 
import numpy as np
medal_predict = [15,12,18]
medal = [21,10,14]

medal_min = [a-b for a,b in zip(medal,medal_predict)]
medal_squr = [x**2 for x in medal_min]
medal_sum = sum(medal_squr)
medal_mean = medal_sum/len(medal)
#print("MSE : {}".format(medal_mean))
print(np.round(medal_mean,3))

18.667


##Xor 문제를 풀기 위해  다층 신경망 구조 로 풀기 
Dense 1개  = 1 layer
1개의 layer 에는 
노드=퍼셉트론 =유닛 이라는 값이 하나 이상 존재 한다.


In [2]:
import tensorflow as tf 
import numpy as np 

x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]]) 


#신경망을 만들떄 일련의 순서 

##1. 데이터를 불러온다 
##2. 신경망 모델을 만든다.
##3. 최적화를 어떻게 할것인지 
##4. 학습 


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(units = 2 , activation= 'elu',input_shape = (2,)),   # 모든 노드를 연결하는 방법 구조 : Dense(unit 의수, activation function,input_shape = ())                                  
  #tuple 은 값이 하나 들어올떄 (2,)
  tf.keras.layers.Dense(units = 5 , activation= 'elu'),
  tf.keras.layers.Dense(units = 7 , activation= 'elu'),
  tf.keras.layers.Dense(units = 1 , activation= 'sigmoid') # 0~1 사이의 값을 출력하기 위해 
] )


신경망 모델을 만드는 방법 2가지

1. 순서적으로
2. 원하는 방식대로 만드는 함수형 방식

최적화

learning rate = 학습률 학습에 정교함을 얼마나 정교하게 할지 수치를 만든다

In [ ]:
model.compile(optimizer = tf.keras.optimizers.Adam(learning_rate = 0.001),
              loss = 'mse')
history = model.fit(x,y,epochs = 1000) #순전파와 역전파를 모두 처리하는 역할이다.



Epoch 1/1000
1/1 [==============================] - 0s 364ms/step - loss: 0.2724
Epoch 2/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.2718
Epoch 3/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.2711
Epoch 4/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.2705
Epoch 5/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2698
Epoch 6/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.2692
Epoch 7/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2687
Epoch 8/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.2681
Epoch 9/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2676
Epoch 10/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2671
Epoch 11/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2666
Epoch 12/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.2661
Epoch 13/1000
1/1 [============================

In [ ]:
#예측 값 보기 
print(model.predict(x))
'''
[[0.02987769]
 [0.9752364 ]
 [0.9784889 ]
 [0.02612764]]
'''

[[0.02987769]
 [0.9752364 ]
 [0.9784889 ]
 [0.02612764]]


one_hot vector
M  F   I 
1  0   0
0  1   0
0  0   1

단점 : 데이터의 수가 많으면 데이터가 영향을 줄정도로 잡아 먹는다.


In [3]:
row1 = ['M',0.455,0.365,0.095]
row2 = ['F',0.455,0.365,0.095]
row3 = ['I',0.455,0.365,0.095]

result = np.zeros((3,3),dtype = np.int32)

if row1[0] == 'M':
  result[0][0] = 1
elif row1[0] == 'F':
  result[0][1] = 1
else:
  result[0][2] = 1
row1[0] = result[0]

if row2[0] == 'M':
  result[1][0] = 1
elif row2[0] == 'F':
  result[1][1] = 1
else:
  result[1][2] = 1
row2[0] = result[1]
if row3[0] == 'M':
  result[2][0] = 1
elif row3[0] == 'F':
  result[2][1] = 1
else:
  result[2][2] = 1
row3[0] = result[2]

print(result)
print(row1,'\n',row2,'\n',row3)

if row1[0] == 'M':
  row1[0] = [1,0,0]
elif row2[0] == 'F':
  row2[0] = [0,1,0]
else:
  row3[0] = [0,0,1]
print(row1,'\n',row2,'\n',row3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[array([1, 0, 0], dtype=int32), 0.455, 0.365, 0.095] 
 [array([0, 1, 0], dtype=int32), 0.455, 0.365, 0.095] 
 [array([0, 0, 1], dtype=int32), 0.455, 0.365, 0.095]
[array([1, 0, 0], dtype=int32), 0.455, 0.365, 0.095] 
 [array([0, 1, 0], dtype=int32), 0.455, 0.365, 0.095] 
 [[0, 0, 1], 0.455, 0.365, 0.095]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:35: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
