In [ ]:
import numpy as np 
import pandas as pd 

df = pd.read_csv('/content/faults.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1941 entries, 0 to 1940
Data columns (total 34 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   X_Minimum              1941 non-null   int64  
 1   X_Maximum              1941 non-null   int64  
 2   Y_Minimum              1941 non-null   int64  
 3   Y_Maximum              1941 non-null   int64  
 4   Pixels_Areas           1941 non-null   int64  
 5   X_Perimeter            1941 non-null   int64  
 6   Y_Perimeter            1941 non-null   int64  
 7   Sum_of_Luminosity      1941 non-null   int64  
 8   Minimum_of_Luminosity  1941 non-null   int64  
 9   Maximum_of_Luminosity  1941 non-null   int64  
 10  Length_of_Conveyer     1941 non-null   int64  
 11  TypeOfSteel_A300       1941 non-null   int64  
 12  TypeOfSteel_A400       1941 non-null   int64  
 13  Steel_Plate_Thickness  1941 non-null   int64  
 14  Edges_Index            1941 non-null   float64
 15  Empt

In [ ]:
df_dataset = df[['X_Minimum','X_Maximum','Steel_Plate_Thickness','LogOfAreas',
                 'Pastry','Z_Scratch','Bumps']]
print("df_dataset.shape : ", df_dataset.shape)
print(df_dataset.info())

df_dataset.shape :  (1941, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1941 entries, 0 to 1940
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   X_Minimum              1941 non-null   int64  
 1   X_Maximum              1941 non-null   int64  
 2   Steel_Plate_Thickness  1941 non-null   int64  
 3   LogOfAreas             1941 non-null   float64
 4   Pastry                 1941 non-null   int64  
 5   Z_Scratch              1941 non-null   int64  
 6   Bumps                  1941 non-null   int64  
dtypes: float64(1), int64(6)
memory usage: 106.3 KB
None


In [ ]:
#데이터 모양을 줄이자
df_dataset = np.asarray(df_dataset, dtype = 'float32')

df_dataset_x = df_dataset[0:1,:-3] #독립변수
df_dataset_y = df_dataset[0:1,-3:] #종속변수

print(df_dataset_x.shape)
print(df_dataset_x)
print(df_dataset_y.shape)
print(df_dataset_y)

(1, 4)
[[42.     50.     80.      2.4265]]
(1, 3)
[[1. 0. 0.]]


In [ ]:
RND_MEAN = 0
RND_STD = 1

input_cnt = df_dataset_x.shape[-1]
ouput_cnt = df_dataset_y.shape[-1]
weight = np.random.normal(RND_MEAN,RND_STD,size = [input_cnt,ouput_cnt]) 
bias = np.random.normal(RND_MEAN,RND_STD,size = [ouput_cnt])

In [ ]:
#값을 확인하는 습관
print(weight)
print(bias)



[[-0.80548971 -0.01629008  1.7478838 ]
 [-0.21743526 -0.13038552 -0.53104539]
 [-0.93967754  1.28839009 -0.47895067]
 [ 1.52852126 -1.3962232  -1.42327355]]
[-1.961189   -0.87170187 -1.13441615]


In [ ]:
#for i in range(ouput_cnt)
p_1 = np.matmul(df_dataset_x[0],weight[:,0]) + bias[0]
p_2 = np.matmul(df_dataset_x[0],weight[:,1]) + bias[1]
p_3 = np.matmul(df_dataset_x[0],weight[:,2]) + bias[2]

#weight bias = (model)parameter 값이 바뀌는 존재 
#learning rate x y mean = hyperparameter 값이 안바뀌는 존재 
print(p_1,p_2,p_3)

result = np.matmul(df_dataset_x,weight) + bias

print(result)

-118.12876618486499 91.60811012587588 3.9548071008042713
[[-118.12876618   91.60811013    3.9548071 ]]


##layer 

###input_layer


###ouput_layer


In [ ]:
df = pd.read_csv('/content/faults_mini.csv')
df.info()
display(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   X_Minimum              10 non-null     int64
 1   Y_Minimum              10 non-null     int64
 2   Pixels_Areas           10 non-null     int64
 3   Steel_Plate_Thickness  10 non-null     int64
 4   Pastry                 10 non-null     int64
 5   Z_Scratch              10 non-null     int64
 6   K_Scatch               10 non-null     int64
dtypes: int64(7)
memory usage: 688.0 bytes


X_Minimum  Y_Minimum  Pixels_Areas  ...  Pastry  Z_Scratch  K_Scatch
0         42     270900           267  ...       1          0         0
1       1084     185575           108  ...       0          0         1
2       1109    1170194           130  ...       0          1         0
3        190     210936           132  ...       1          0         0
4        330     429227           264  ...       1          0         0
5         74     779144          1506  ...       1          0         0
6         51     585861           139  ...       0          1         0
7        397     604478           444  ...       0          1         0
8         43     366881          4048  ...       0          0         1
9         48     377537          3985  ...       0          0         1

[10 rows x 7 columns]

In [ ]:
df = np.asarray(df,dtype = 'float32')

In [ ]:
#데이터의 weight 와 bias 수행 
RND_MEAN = 0
RND_STD = 1

input_cnt = df_dataset_x.shape[-1]
ouput_cnt = df_dataset_y.shape[-1]
weight = np.random.normal(RND_MEAN,RND_STD,size = [input_cnt,ouput_cnt]) 
bias = np.random.normal(RND_MEAN,RND_STD,size = [ouput_cnt])

print(weight)

print(bias)

[[-0.92003497  1.14986169 -0.66388318]
 [-0.49385575  0.65172601  0.30437332]
 [ 1.4493316  -1.14207876 -0.56343449]
 [ 1.21684002  0.77625513 -1.20560301]]
[-1.2901458  -0.52299326  0.01876084]


In [ ]:
#train test split 
mb_size = 2
train_ratio = 0.8

df.shape #10,7
df.shape[0] * train_ratio #학습 데이터의 개수 

mb_step_count = df.shape[0] * train_ratio // mb_size #미니배치 사이즈를 통한 갯수
print(mb_step_count)

4.0


In [ ]:
#train_test 경계 
test_begin_index = mb_size * mb_step_count
print(test_begin_index)

shffle_map = np.arange(df.shape[0])
np.random.shuffle(shffle_map)

print(shffle_map)

8.0
[4 9 5 0 6 3 1 2 8 7]


In [ ]:
mb_data_1 = df[shffle_map[0:2]]
print(mb_data_1)

mb_data_2 = df[shffle_map[2:4]]
print(mb_data_2)

mb_data_3 = df[shffle_map[4:6]]
print(mb_data_3)

mb_data_4 = df[shffle_map[6:8]]
print(mb_data_4)

[[3.30000e+02 4.29227e+05 2.64000e+02 1.50000e+02 1.00000e+00 0.00000e+00
  0.00000e+00]
 [4.80000e+01 3.77537e+05 3.98500e+03 4.00000e+01 0.00000e+00 0.00000e+00
  1.00000e+00]]
[[7.40000e+01 7.79144e+05 1.50600e+03 1.50000e+02 1.00000e+00 0.00000e+00
  0.00000e+00]
 [4.20000e+01 2.70900e+05 2.67000e+02 8.00000e+01 1.00000e+00 0.00000e+00
  0.00000e+00]]
[[5.10000e+01 5.85861e+05 1.39000e+02 7.00000e+01 0.00000e+00 1.00000e+00
  0.00000e+00]
 [1.90000e+02 2.10936e+05 1.32000e+02 1.50000e+02 1.00000e+00 0.00000e+00
  0.00000e+00]]
[[1.084000e+03 1.855750e+05 1.080000e+02 4.000000e+01 0.000000e+00
  0.000000e+00 1.000000e+00]
 [1.109000e+03 1.170194e+06 1.300000e+02 1.750000e+02 0.000000e+00
  1.000000e+00 0.000000e+00]]


In [ ]:
mb_data_1_x = mb_data_1[:,:-3]
mb_data_1_y = mb_data_1[:,-3:]

print(mb_data_1_x)
print(mb_data_1_y)
mb_data_2_x = mb_data_2[:,:-3]
mb_data_2_y = mb_data_2[:,-3:]

print(mb_data_2_x)
print(mb_data_2_y)

mb_data_3_x = mb_data_3[:,:-3]
mb_data_3_y = mb_data_3[:,-3:]

print(mb_data_3_x)
print(mb_data_3_y)

mb_data_4_x = mb_data_4[:,:-3]
mb_data_4_y = mb_data_4[:,-3:]
print(mb_data_4_x)
print(mb_data_4_y)


[[3.30000e+02 4.29227e+05 2.64000e+02 1.50000e+02]
 [4.80000e+01 3.77537e+05 3.98500e+03 4.00000e+01]]
[[1. 0. 0.]
 [0. 0. 1.]]
[[7.40000e+01 7.79144e+05 1.50600e+03 1.50000e+02]
 [4.20000e+01 2.70900e+05 2.67000e+02 8.00000e+01]]
[[1. 0. 0.]
 [1. 0. 0.]]
[[5.10000e+01 5.85861e+05 1.39000e+02 7.00000e+01]
 [1.90000e+02 2.10936e+05 1.32000e+02 1.50000e+02]]
[[0. 1. 0.]
 [1. 0. 0.]]
[[1.084000e+03 1.855750e+05 1.080000e+02 4.000000e+01]
 [1.109000e+03 1.170194e+06 1.300000e+02 1.750000e+02]]
[[0. 0. 1.]
 [0. 1. 0.]]


In [40]:
mb1_yhat0 = np.matmul(mb_data_1_x,weight[:,0]) + bias[0]
mb1_yhat1 = np.matmul(mb_data_1_x,weight[:,1]) + bias[1]
mb1_yhat2 = np.matmul(mb_data_1_x,weight[:,2]) + bias[2]

print(mb1_yhat0)
print(mb1_yhat1)
print(mb1_yhat2)
print('\n')
mb2_yhat0 = np.matmul(mb_data_2_x,weight[:,0]) + bias[0]
mb2_yhat1 = np.matmul(mb_data_2_x,weight[:,1]) + bias[1]
mb2_yhat2 = np.matmul(mb_data_2_x,weight[:,2]) + bias[2]

print(mb2_yhat0)
print(mb2_yhat1)
print(mb2_yhat2)
print('\n')
mb3_yhat0 = np.matmul(mb_data_3_x,weight[:,0]) + bias[0]
mb3_yhat1 = np.matmul(mb_data_3_x,weight[:,1]) + bias[1]
mb3_yhat2 = np.matmul(mb_data_3_x,weight[:,2]) + bias[2]

print(mb3_yhat0)
print(mb3_yhat1)
print(mb3_yhat2)
print('\n')
mb4_yhat0 = np.matmul(mb_data_4_x,weight[:,0]) + bias[0]
mb4_yhat1 = np.matmul(mb_data_4_x,weight[:,1]) + bias[1]
mb4_yhat2 = np.matmul(mb_data_4_x,weight[:,2]) + bias[2]

print(mb4_yhat0)
print(mb4_yhat1)
print(mb4_yhat2)

[-211715.97616086 -180670.01185391]
[279932.2595544  241585.21815578]
[130096.59818088 112586.8328164 ]


[-382488.90147484 -133341.1368221 ]
[506269.44226246 176357.51181711]
[236072.16647699  82179.98343964]


[-289092.40233605 -103974.21648823]
[381774.55892291 137656.11156768]
[178123.91011212  63821.95827241]


[ -92440.68831917 -578527.28982629]
[122097.68648562 763907.91080707]
[ 55655.37363682 355155.3808587 ]


In [43]:
mbtotal = np.vstack((mb_data_1,mb_data_2,mb_data_3,mb_data_4))

mb_total_train_x = mbtotal[:,:-3]
total = np.matmul(mb_total_train_x , weight) + bias

print(total)

[[-211715.97616086  279932.2595544   130096.59818088]
 [-180670.01185391  241585.21815578  112586.8328164 ]
 [-382488.90147484  506269.44226246  236072.16647699]
 [-133341.1368221   176357.51181711   82179.98343964]
 [-289092.40233605  381774.55892291  178123.91011212]
 [-103974.21648823  137656.11156768   63821.95827241]
 [ -92440.68831917  122097.68648562   55655.37363682]
 [-578527.28982629  763907.91080707  355155.3808587 ]]
