Numpy
ndarray : n차원의 배열을 소유하고 있음
list : 동적 할당 array: 정적 할당

In [2]:
# 구글드라이브 연동
from google.colab import drive
drive.mount('/gdrive', force_remount=True)

# 구글 드라이브 파일 확인
!ls '/gdrive/My Drive/temp/'

# 반복되는 드라이브 경로 변수화
drive_path = '/gdrive/My Drive/temp/'

Mounted at /gdrive
 매수종목1.txt		   little-char.png	   sonar.csv
 매수종목2.txt		   ml_class.png		   stock-data.csv
 adult.data		   pca_1.png		  'stock price.xlsx'
 auto-mpg.csv		   pca_2.png		  'stock valuation.xlsx'
 bmi_500.csv		   pca_3.png		   test.db.db
 citibike.csv		   Picture1.png		   test.txt
 매수종목.csv		   population_number.csv   text.txt
 data_mine.csv		   ram_price.csv	   ThoraricSurgery.csv
 data_population.csv	   ratings_small.txt	   titanic.xls
 data_studentlist_en.csv   ratings_test.txt	   tmdb_5000_credits.csv
 demo.docx		   ratings_train.txt	   tmdb_5000_movies.csv
 diabetes.csv		   sample1.pdf		   Traffic_Accident_2017.csv
 example.docx		   sample2.pdf		   train.csv
 height_weight.txt	   sample.docx		   user_id_mean.csv
 HelloWorld.xlsx	   sample_merge.pdf	   wine.csv
 house_price.csv	   sample.xlsx		   주가데이터.xlsx
 lenna.png		   score.csv		   남북한발전전력량.xlsx


* 머신러닝 라이브러리
 * 사이킷런(Scikit-Learn)
* 행렬/선형대수/통계 라이브러리
  * **넘파이(NumPy): 고성능 과학계산을 위한 데이터 분석**(행렬, 선형대수)
  * 사이파이(SciPy): 자연과학, 통계
* 데이터 핸들링
 * 판다스(Pandas): 행과 열로 구성된 표 형식의 데이터(2차원 데이터 처리)
* 시각화
 * 맷플롯립(Matplotlib): 2D 그래프로 시각화
 * 시본(Seaborn): 다양한 색상 테마로 시각화

# Numpy (Numerical Python)
- 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공
- 빠르고 효율적인 벡터 산술연산을 제공하는 n 차원 배열 (ndarray)
- 반복문 없이 전체 데이터 배열 연산이 가능한 표준 수학 함수 (sum(), sqrt(), mean())
- 선형대수, 난수 생성, 푸리에 변환

In [3]:
import numpy as np

In [4]:
np.__version__

'1.19.5'

numpy.ndarray

- 동일한 자료형을 가지는 값들이 배열 형태로 존재함
- N 차원 형태로 구성이 가능하다.
- 각 값들은 양의 정수로 색인(index)가 부여되어 있다.
- Numpy에서 차원(Dimension)을 rank, axis라고 부르기도 한다.
- ndarray를 줄여서 array로 표현한다.


In [5]:
list = [1,2,3]
array1 = np.array(list)

print(type(array1),array1.shape) #array1.shape array 의 모양 확인 

array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(array2),array2.shape)

array3 = np.array([[1,2,3]])#2차원 행렬인데 1,3
print(type(array3),array3.shape)

<class 'numpy.ndarray'> (3,)
<class 'numpy.ndarray'> (3, 3)
<class 'numpy.ndarray'> (1, 3)


ndarray.shape

해당 array의 크기를 알 수 있다.

- ndarray의 차원과 크기를 튜플(tuple) 형태로 출력

- shape 을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.

- 위에서 array1.shape의 결과는 (3,) 으로써, 1차원의 데이터이며 총 3라는 크기를 갖고 있음을 알 수 있다.

- array2.shape의 결과는 (2,3) 으로써, 2차원의 데이터이며 2 * 3 크기를 갖고 있는 array 이다.


In [6]:
print(array1.ndim) #ndim : 차원 확인 
print(array2.ndim)
print(array3.ndim)


1
2
2


In [7]:
print(array1.size) #총 원소의 개수 size
print(array2.size)
print(array3.size)

3
9
3


numpy에서 사용되는 자료형

- 부호가 있는 정수 int(8, 16, 32, 64)
- 부호가 없는 정수 uint(8 ,16, 32, 54)
- 실수 float(16, 32, 64, 128)
- 복소수 complex(64, 128, 256)
- 불리언 bool
- 문자열 string_
- 파이썬 오프젝트 object
- 유니코드 unicode_


In [8]:
#ndarray는 한종류의 데이터만 들어가야 한다.
list1 = [1,2,3]
print(type(list1))
array4 = np.array(list1)
print(array1.dtype)

list2 = [1,2,3,'test']
print(type(list2))
array5 = np.array(list2)
print(array5.dtype) #완전히 다른 타입이기 때문에 U21 코드로 인식함.
array5 #모든 데이터를 포함하는 원소로 설정하게 된다.

list3 = [1,2,3.0]
array6 = np.array(list3)
print(array6.dtype) #float 로 모든 타입을 통일 하여 출력
array6

<class 'list'>
int64
<class 'list'>
<U21
float64


array([1., 2., 3.])

- 리스트와 다르게 ndarray는 같은 데이터 타입만 가능.
- 서로 다른 데이터 타입이 섞여 있을 경우 큰 데이터 타입으로 형 변환을 일괄 적용

In [9]:
array_int = np.array([1,2,3])
print(array_int,array_int.dtype)
array_float = array_int.astype('float64') #자료형 강제 형변환 가능
print(array_float,array_float.dtype)

[1 2 3] int64
[1. 2. 3.] float64


In [10]:
#타입 생성 지정 
array7 = np.array([1.1,2.2,3.3],dtype=np.int64)
print(array7,array7.shape,array7.dtype)

[1 2 3] (3,) int64


Numpy 예제 1

In [11]:
array8 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("배열의 크기:",array8.shape)
print("배열의 차원:",array8.ndim)
print("배열의 개수:",array8.size)

배열의 크기: (2, 2, 2)
배열의 차원: 3
배열의 개수: 8


ndarray 생성


In [12]:
#연속값으로 생성 하는 방법 
array_9 = np.arange(10) #arange 로 사용하여 넘파이 배열을 만들수 있다
print(array_9,array_9.shape,array_9.ndim)

[0 1 2 3 4 5 6 7 8 9] (10,) 1


In [13]:
array_10 =  np.zeros([3,5]) #모든 원소가 0인 데이터 만들기 기본 초기화 : float32
print(array_10,array_10.dtype,array_10.shape,array_10.ndim,array_10.size)
array_11 = np.ones([10,10],dtype = np.int32) #모든 원소를 1로 채운 배열 만들기 
print(array_11,array_11.dtype,array_11.shape,array_11.ndim,array_11.size)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] float64 (3, 5) 2 15
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]] int32 (10, 10) 2 100


In [14]:
#특정값으로 초기화 하고 싶을떄 
array_13 = np.full([5,5],7)
print(array_13,array_13.shape,array_13.ndim,array_13.size)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]] (5, 5) 2 25


In [15]:
#랜덤 값 초기화 
np.random.seed(10)
array_14 = np.random.randint(2,10,size = (2,3))
print(array_14,array_14.shape,array_14.ndim,array_14.size)

[[3 7 6]
 [9 2 3]] (2, 3) 2 6


numpy 예제 2


In [56]:
np.arange(1,51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

ndarray 차원가 크기 변경

In [17]:
array_15 = np.arange(10)
print(array_15)
print(array_15.reshape(2,5)) #모양을 바꾸고 싶을때 사용한다 단 모양의 크기와 원소의 개수가 맞아야 한다 reshape(행,열)
array_16 = array_15.reshape(2,5)
print(array_16.ndim,array_16.shape)
#array_3 = array_1.reshape(5,2) 다른 ndarray 에 대입해서 사용가능 
#print(array_3)
array17 = array_15.reshape(-1,5) #행은 자동호환 기능이 있어서 -1 로 표현 가능하다 .

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
2 (2, 5)


In [18]:
array_18 = np.arange(8)
array_19 = array_18.reshape((2,2,2)) #3차원 역시 개수와 모양이 맞으면 가능하다.
print(array_19.reshape(-1,1))
print(array_19.tolist()) #넘파이를 리스트로 변경하는 소스 
print(array_18.reshape(-1,1))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


### ndarray 인덱싱 & 슬라이싱
- 특정 데이터 추출
- 슬라이싱(Slicing) : 연속된 데이터 추출
- 팬시 인덱싱(Fancy Indexing) : 리스트 또는 ndarray 형태의 인덱싱 집합을 이용하여 여러 데이터를 추출
- 불린 인덱싱(Boolean Indexing) : True/False 값 인덱싱 집합을 이용하여 해당 인덱스 위치에 있는 데이터를 추출

In [19]:
array_20 = np.arange(1,10)
print(array_20)

[1 2 3 4 5 6 7 8 9]


In [20]:
print(array_20[-1]) #-1 index 는 뒤에서 부터 시작한다
print(array_20[-2])
array_20[0] = 10 #바로 접근해서 숫자변경 가능
print(array_20)

9
8
[10  2  3  4  5  6  7  8  9]


In [21]:
array_21 = np.arange(1,10)
array_212D = array_21.reshape(3,3)
print(array_212D[0,0])
print(array_212D[0][0]) #위에줄과 같은 결과 1
print(array_212D[0][1])
print(array_212D[0,1])  
print(array_212D[1,0])
print(array_212D[1][0])    
print(array_212D[2,2])
print(array_212D[2][2]) 


1
1
2
2
4
4
9
9


슬라이싱
- ':' 기호 앞에 시작 인덱스를 생략하면 맨 처음 인덱스인 0으로 간주
- ':' 기호 뒤에 종료 인덱스를 생략하면 맨 마지막 인덱스로 간주
- ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 맨 처음/마지막 인덱스로 간주



In [22]:
array_22 = np.arange(1,10)
print(array_22)
print(array_22[:3]) # print(array_22[0:3]) 같은 결과이다 
print(array_22[3:])
print(array_22[:])



[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [23]:
array_23 = np.arange(1,10).reshape(3,3)
print(array_23)

print(array_23[:2,:2])
print(array_23[1:])
print(array_23[1:,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[5]
 [8]]


팬시 인덱싱

In [24]:
array_24 = np.arange(1,10)
print(array_24)
print(array_24[[2, 4, 7]])

[1 2 3 4 5 6 7 8 9]
[3 5 8]


In [25]:
#2차원 
array_25 = np.arange(1,10).reshape(3,3)
print(array_25)
array_25[[0,2],[2]] #0,2 의 인덱싱 위치에 있는 행에 마지막 원소 가져오기 
print(array_25[[0,2],:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]


불린 인덱싱

In [26]:
array_25 = np.arange(1,10)

array_25[array_25>5] #[] 안에 조건식을 넣어서 인덱싱 하는 방법 
array_25>5 # 각 요소별로 불린 값을 계산 

array([False, False, False, False, False,  True,  True,  True,  True])

In [27]:
#불린 인덱싱 응용
name = np.array(['홍길동','박철수','이해수','김영원','을지문덕'])
name_score = np.array([[60,60],[70,70],[80,80],[90,90],[100,100]])
print(name_score)

[[ 60  60]
 [ 70  70]
 [ 80  80]
 [ 90  90]
 [100 100]]


In [28]:
name == '홍길동' #이름으로
name_score == [60,60]
name_score[name == '홍길동'] #index 위치가 같으면 두 배열이 하나가 아니여도 바로 가져올수 있음

array([[60, 60]])

#### Numpy 예제 03 

BMI 구하기

10명에 대한 키와 몸무게가 들어있는 파일 ‘height_weight.txt’을 읽어 각 사람별 BMI 지수를 구하시오.
```
data = np.loadtxt(drive_path + "height_weight.txt", delimiter = ",") # delimiter : 구분자
data
```
  \\( BMI지수=\frac { 몸무게(kg) }{ 키(m) \times 키(m) } \\)
```
# 제곱 계산
# **2 or np.square()
```

In [29]:
data = np.loadtxt(drive_path +"height_weight.txt",delimiter="," ) #delimiter = 구분자
data
data_height = data[:1,]
data_weight = data[1:]
print(data)
print(data_height,data_weight)

data_BMI = np.array(data_weight/(data_height/100)**2)

print(data_BMI)

[[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]
 [ 65.6  88.   79.2  69.3  55.   71.2  73.   68.9  74.   82. ]]
[[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]] [[65.6 88.  79.2 69.3 55.  71.2 73.  68.9 74.  82. ]]
[[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
  23.14392095 21.69720651 23.62028791 25.59220998]]


### 행렬의 정렬
- sort() : 정렬
- argsort() : 정렬된 행렬의 원본 행렬 원소에 대한 인덱스를 반환

In [30]:
org_array = np.array([3,1,8,5])
sort_array = np.sort(org_array)
print(sort_array)
argsort_array = np.argsort(org_array)
print(argsort_array)

[1 3 5 8]
[1 0 3 2]


In [31]:
org_array[::-1] #내림차순 으로 정렬 증감 연산자 를 -1 로주면 내림차순 효과를 볼수 있다.

array([5, 8, 1, 3])

In [32]:
np.sort(org_array)[::-1] #정렬한 arr 를 -1 연산자를 사용하여 reverse 역할 을 한다.

array([8, 5, 3, 1])

In [33]:
#2차원 sort
array = np.array([[8,12],
                  [7,1]])
print(np.sort(array,axis = 0)) #2차원 배열을 행과 열의 방향 축을 axis 매개변수로 정하여 정렬을 할수 있다.axis = 0 (열) axis = 1(행)


[[ 7  1]
 [ 8 12]]


In [34]:
org_array = np.array([3,1,8,5])
np.argsort(org_array)

array([1, 0, 3, 2])

In [35]:
#불린 인덱싱 응용
name = np.array(['홍길동','박철수','이해수','김영원','을지문덕'])
name_score = np.array([78,95,84,98,88])
sort_index = np.argsort(name_score)[::-1]
name[sort_index]


array(['김영원', '박철수', '을지문덕', '이해수', '홍길동'], dtype='<U4')

### ndarray 연산
- 일반연산 : 산술연산, 비교연산 ...
- 선형대수 연산 : 행렬 내적과 전치 행렬

In [36]:
array = np.array([1,2,3])
array+100 #모든 일반적인 연산이 전체 요소에 적용
array + array
array*array
array - array
np.subtract(array,array)
array == 1

array([ True, False, False])

In [37]:
array == array

array([ True,  True,  True])

In [38]:
#행렬의 내적
A = np.array([[5,4],[1,9]])
B = np.array([[4,6],[8,2]])
np.dot(A,B) #행렬의 내적 메소드 

array([[52, 38],
       [76, 24]])

In [39]:
#전치 행렬 
array = np.array([[1,2,3]
                  ,[4,5,6]])
np.transpose(array) #행과 열의 크기를 바꾼다 (2,3) ->(3,2)
array.T #대문자 T로도 전치 행렬을 사용할수 있다.

array([[1, 4],
       [2, 5],
       [3, 6]])

### Universal 함수
- sin(), cos()다양한 수학함수를 제공
- 스칼라값을 입력으로 하는 math 패키지와 달리 배열에 대해 요소별로 적용

In [40]:
array = np.arange(1,10)
array.sum()

45

In [41]:
array.mean()

5.0

In [42]:
array.max()

9

In [43]:
array.min()

1

In [44]:
array = np.array([-1,-2,3,-4,-5])
np.abs(array)

array([1, 2, 3, 4, 5])

영화 평점 데이터 분석

In [45]:
data = np.loadtxt(drive_path + "ratings_small.txt",
                  delimiter="::",dtype = np.int64)
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     1779,      2502,         4, 998699749],
       [     1779,      3160,         5, 977032398],
       [     1779,      3168,         4, 977033232]])

##### 데이터 분석하기
```
print(data.ndim)
print(data.shape)
print(data.size)
```

In [46]:
print(data.ndim)
print(data.shape)
print(data.size)

2
(300001, 4)
1200004


##### 전체 평점 평균 구하기
1. 평점 데이터만 추출 (인덱싱, 슬라이싱)
2. 평균 구하기 (mean)

In [47]:
movie_score = data[0:,2:3]
movie_score
movie_score.mean()

3.5613081289729034

##### 각 사용자별 평점 평균 구하기
1번 사용자의 평균 평점 구하기
1. 1번 사용자의 데이터만 Boolean Indexing 추출
2. 1번 사용자의 데이터에서 평점만 추출 (인덱싱, 슬라이싱)
3. 평균 구하기

참고
```
# 중복된 성분을 제외한 array를 반환
np.unique( ndarray )
```

In [48]:
user_id_all = np.unique(data[:,0]) #중복없이 한번만 나오는지 알아내는 함수 


In [49]:
user_1 = data[data[:,0] == 1]
np.mean(user_1[0:,2:3])

4.188679245283019

In [55]:
person = data[:,:1]
one_person = np.array(person == 1).reshape(-1,)
print(one_person)
#one_person.reshape(1,)
score = data[:,2]
print(score)
one_scoreMean = np.mean(score[one_person == True])
one_scoreMean
#score[]

[ True  True  True ... False False False]
[5 3 3 ... 4 5 4]


4.188679245283019

In [51]:
#각 사용자별 평점 평균 
score_mean = []
for i in range(len(user_id_all)):
  score_mean.append([i,data[data[:,0]==i][:,2].mean()])
for i in range(len(score_mean)):
  print(i+1,"번쨰 아이디 평균:",score_mean[i])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: Mean of empty slice.
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


1 번쨰 아이디 평균: [0, nan]
2 번쨰 아이디 평균: [1, 4.188679245283019]
3 번쨰 아이디 평균: [2, 3.7131782945736433]
4 번쨰 아이디 평균: [3, 3.9019607843137254]
5 번쨰 아이디 평균: [4, 4.190476190476191]
6 번쨰 아이디 평균: [5, 3.1464646464646466]
7 번쨰 아이디 평균: [6, 3.9014084507042255]
8 번쨰 아이디 평균: [7, 4.32258064516129]
9 번쨰 아이디 평균: [8, 3.884892086330935]
10 번쨰 아이디 평균: [9, 3.7358490566037736]
11 번쨰 아이디 평균: [10, 4.114713216957606]
12 번쨰 아이디 평균: [11, 3.2773722627737225]
13 번쨰 아이디 평균: [12, 3.8260869565217392]
14 번쨰 아이디 평균: [13, 3.388888888888889]
15 번쨰 아이디 평균: [14, 3.32]
16 번쨰 아이디 평균: [15, 3.3233830845771144]
17 번쨰 아이디 평균: [16, 3.0285714285714285]
18 번쨰 아이디 평균: [17, 4.075829383886256]
19 번쨰 아이디 평균: [18, 3.6491803278688524]
20 번쨰 아이디 평균: [19, 3.5725490196078433]
21 번쨰 아이디 평균: [20, 4.083333333333333]
22 번쨰 아이디 평균: [21, 2.909090909090909]
23 번쨰 아이디 평균: [22, 3.0673400673400675]
24 번쨰 아이디 평균: [23, 3.3157894736842106]
25 번쨰 아이디 평균: [24, 3.948529411764706]
26 번쨰 아이디 평균: [25, 3.7411764705882353]
27 번쨰 아이디 평균: [26, 2.96]
28 번쨰 아이디 평균: [27, 4

###### 질문

평점 4점이 넘는 사용자만 구하려면,
user_rate_avg의 결과 값을 리스트로 모은 후 ndarray 형식으로 바꾸는 방법밖에 없나요?

In [58]:
score_array = np.array(score_mean)
score_array
#score_mean.append([i+1,data[data[:,0]==i][:,2].mean()])
print(score_array[score_array[:,1]>=4.0][:,0].astype('int')) #score_array[조건][슬라이싱 범위].astype(설정자료형 )

[   1    4    7   10   17   20   27   36   43   46   53   54   55   64
   65   67   69   74   75   76   81   82   86   88   91   97  101  103
  105  106  109  112  121  124  125  126  128  129  130  138  150  152
  153  156  158  161  162  164  171  177  183  184  186  187  189  196
  205  210  213  215  220  222  228  230  231  233  234  235  239  244
  246  248  252  255  257  259  265  266  270  274  275  283  285  288
  291  297  299  300  307  309  311  313  316  320  322  325  330  332
  336  339  341  343  345  346  356  366  367  372  374  375  376  379
  381  382  399  404  408  412  413  417  420  421  427  434  437  444
  446  447  450  451  452  455  466  469  472  473  485  486  494  496
  502  503  505  514  518  521  523  525  527  529  530  537  538  543
  553  564  567  568  574  577  582  583  584  586  588  589  590  592
  594  597  605  606  607  609  615  617  623  625  626  630  634  635
  636  638  640  641  642  645  653  657  661  664  671  674  681  682
  690 

csv 파일로 저장


In [61]:
np.savetxt(drive_path + "user_id_mean.csv",score_mean,delimiter=',',fmt = "%.3f")

Numpy 요약

In [ ]:
import numpy as np

In [62]:
#리스트는 크기가 바뀔수 있다. >>>동적
#array 는 항상 선언시 모양을 만들어야 한다.>>> 정적
np.linspace(0,10,num =5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])